### ISSUE TITLE
Introduction to hierarchical state machine

### ISSUE THREAD

**Issue by lxcid** [tarbrain/TBStateMachine#14]
Do you have any links or papers that describe hierarchical state machine well? Maybe adding them to the README will be nice.

**Comment by tarbrain** [comment]
Hello lxcid,

this library is based on the UML State Machine as described here:

http://en.wikipedia.org/wiki/UML_state_machine
http://www.omg.org/spec/UML/2.5/Beta2/

There are also useful implementations in other languages as well:

https://github.com/steelbreeze/state.js
https://github.com/Mask/hsm-js
https://github.com/artcom/hsm-rb
https://github.com/artcom/hsm-java

Cheers
tarbrain
