### ISSUE TITLE
Add debug method to visualize state machine. 

### ISSUE THREAD

**Issue by flagman** [tarbrain/TBStateMachine#17]
Minimal implementation can be as following. 
[stateMachine umpleRepresentation];
```
#=>
class CourseSection
{
  status
  {
    Planned {
      openRegistration -> NotEnoughStudents;
    }
    Open {
      cancel -> Cancelled;
      NotEnoughStudents {
        closeRegistration -> Cancelled;
        register [getClassSize() > getMinimumClassSize()] -> EnoughStudents;
      }
      EnoughStudents {
        closeRegistration -> Closed;
        register [getClassSize() > getMaximumClassSize()] -> Closed;
      }
    }
    Cancelled {}
    Closed {}
  }
}
```
Graphical representation:
http://cruise.eecs.uottawa.ca/umpleonline/umple.php?model=160218638587&diagramtype=state

**Comment by tarbrain** [comment]
I am not sure if this feature makes sense. It would be more the part of a modeling tool, not the actual library. If the Umple online tool could generate objective-c code that would be more practical.

I think looking at the objective-c code you have written is enough visualization.
