### ISSUE TITLE
sub state selected automatically

### ISSUE THREAD

**Issue by adriantofan** [tarbrain/TBStateMachine#18]
Hello,

I am playing with the state machine and I have the following example

```
  TBSMStateMachine *sm = [TBSMStateMachine stateMachineWithName:@"SM"];
  TBSMStateMachine *smA = [TBSMStateMachine stateMachineWithName:@"SMA"];
  TBSMSubState *a = [TBSMSubState subStateWithName:@"A"];
  TBSMState *a1 = [TBSMState stateWithName:@"A1"];
  TBSMState *a2 = [TBSMState stateWithName:@"A2"];
  smA.states = @[a1,a2];
  a.stateMachine = smA;
  sm.states = @[a];
  sm.initialState = a;
  [sm setUp:nil];
```
I've noticed that A1 is the default state of SMA by default and it's `enterBlock` is called at setup.

It is not possible to be in state A and not be in the same time in state A1?

Please help me understand what I am missing,

Thank you

**Comment by tarbrain** [comment]
It depends on which state you set as the initial state of the sub state machine.
If you set

```objc
smA.initialState = a2;
```
or
```objc
smA.states = @[a2, a1];
```
It will enter `a2` at setup.

**Comment by adriantofan** [comment]
Thank you for the answer. 

Can you tell me what can I do to be only in state A without being in state A1 ?

**Comment by tarbrain** [comment]
This is not possible. According to the UML specification state `A` is only a containing state, so the sub-statemachine below must be in a defined state.

As a workaround you could add another state called `idle` which does nothing and add a transition to `a1`  when you need it. But honestly, at this point you should consider re-evaluating you state-model. If A and A1 do not depend on each other they should not be nested. Maybe A1 should be called B instead :smiley:

**Comment by adriantofan** [comment]
Ok , I will try with idle. But I believe that I am rising a valid point. Here is how I see it:

A is a general UI state state with substates A1 and A2 depending on user interactions. 
It is useful to transition from state B to state A without going deeper. 
This is why i've shown you the diagram from wikipedia, where s2 automatically selects s21 opposed to s1. 
Am I misunderstanding this use case and associated diagram ?

**Comment by tarbrain** [comment]
Ok. The diagram is a bit simplified. Usually you would only need s1 and s2. The nested states are only necessary in this model if you had other substates to switch between.

For example:
If you had s1 containing s11 and s12 and you could switch between them with a transition. Or you would want to go directly from s21 to s12 but only under certain conditions.

**Comment by tarbrain** [comment]
Hi @adriantofan ,
I have looked into the UML spec for state machines  (http://www.omg.org/spec/UML/2.5/Beta2/PDF) and on page 324 it says:

> _Direct entry:_ [....] If no initial Pseudostate is defined, there is no single approach defined. One alternative is to treat such a model as ill formed. A second alternative is to treat the composite State as a simple State, terminating the traversal on that State despite its internal parts.

I think we have an edge case here and typically the specification is very vage when it comes to edge cases.
We can either say:
- S1 is malformed because the sub-state configuration is undefined on entry or
- S1 is allowed to be undefined as long as no sub-state has been entered

In my opinion the first point is better because it forces the state configuration being consistent at any time. This helps you to develop state-models which are very consistent, reliable and robust.

Best regards
tarbrain

**Comment by adriantofan** [comment]
Ok,  thank you. For the moment I'l go with the default dummy state and see how is that feeling. I believe that my wish to group the sub states  together and abstract common behavior then specialize substates is valid. 
I will also review David Harel's paper about state charts which  at the origin of this kind of state machine, maybe it will help me understand better how to have a good design.

**Comment by adriantofan** [comment]
Can you also confirm that, in my initial example, it is not possible to make a transition between a and a1? At least I am not able to do it.

**Comment by tarbrain** [comment]
Yes. You can not do that.
